version: '3'
services:
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  elasticsearch:
    image: "elasticsearch:latest"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elasnetwork
  kibana:
    image: "kibana:latest"
    ports:
      - "5601:5601"
    networks:
      - elasnetwork
    links:
      - elasticsearch
networks:
  elasnetwork: